# API call for creating a user

###
POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{
    "username":"react",
    "password":"react@123",
    "email":"react@gmail.com",
    "phone":"8534567890"
}

###
POST http://127.0.0.1:8000/issues/
Content-Type: application/json
Authorization: Token 940004414d4bc67f25273cb1f0f1332451c8cf64

{
    "title":"pipe break",
    "description":"pothole in road",
    "issue_type":"pothole",
    "location":"m.g road"
}

###
GET http://127.0.0.1:8000/issues/
Accept: application/json
Authorization: Token 940004414d4bc67f25273cb1f0f1332451c8cf64

###
GET http://127.0.0.1:8000/issues/2/
Accept: application/json
Authorization: Token 940004414d4bc67f25273cb1f0f1332451c8cf64

###
PUT http://127.0.0.1:8000/issues/3/
Content-Type: application/json
Authorization: Token 940004414d4bc67f25273cb1f0f1332451c8cf64

{
    "title": "water pipe breakage",
    "description": "heavy water leakage",
    "issue_type": "road_damage",
    "location": "M.G road"
}

###
DELETE http://127.0.0.1:8000/issues/1/
Content-Type: application/json
Authorization: Token 940004414d4bc67f25273cb1f0f1332451c8cf64

# token
###
POST http://127.0.0.1:8000/tokens/
Content-Type: application/json

{
    "username":"react",
    "password":"react@123"
}

# django:940004414d4bc67f25273cb1f0f1332451c8cf64
# react:9eb6a71e2aa6491d34ea1c503a1b02c11794fbef

###
POST http://127.0.0.1:8000/issue/3/comments/
Content-Type: application/json
Authorization: Token 940004414d4bc67f25273cb1f0f1332451c8cf64

{
    "message":"high flow of water..."
}

###
GET http://127.0.0.1:8000/comments/1/
Accept: application/json
Authorization: Token 940004414d4bc67f25273cb1f0f1332451c8cf64

###
PUT http://127.0.0.1:8000/comments/1/
Content-Type: application/json
Authorization: Token 940004414d4bc67f25273cb1f0f1332451c8cf64

{
    "message": "no street light for last few months...."
}

###
DELETE http://127.0.0.1:8000/comments/1/
Accept: application/json
Authorization: Token 940004414d4bc67f25273cb1f0f1332451c8cf64

###
POST http://127.0.0.1:8000/issues/2/like/
Content-Type: application/json
Authorization: Token 9eb6a71e2aa6491d34ea1c503a1b02c11794fbef